language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
install:
   - pip install Django==$DJANGO --use-mirrors
   - pip install -r requirements.txt --use-mirrors
env:
  - DJANGO="1.3.3"
  - DJANGO="1.4.1"
  - DJANGO="1.5.1"
script: python setup.py test
